# Generated by Django 5.2.13 on 2026-09-02 21:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_share_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="savings_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="core.savingsgoal",
            ),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
