# Generated by Django 5.2.13 on 2026-09-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_expense_savings_goal_savingsgoal_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
