# Generated by Django 5.2.13 on 2026-09-03 02:24

from django.db import migrations


def drop_duplicate_budgets(apps, schema_editor):
    """The 0006 category merge could leave one person two budgets on a category."""
    Budget = apps.get_model("core", "Budget")
    seen = set()
    for budget in Budget.objects.order_by("id"):
        key = (budget.user_id, budget.category_id)
        if key in seen:
            budget.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_transaction_category"),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_budgets, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category")},
        ),
    ]
