name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
          ${{ secrets.DOCKER_USERNAME }}/expense-tracker:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy locally (pull and run)
      run: |
        docker stop expense-tracker || true
        docker rm expense-tracker || true
        
        docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
        
        docker run -d \
          --name expense-tracker \
          -p 8000:8000 \
          --restart unless-stopped \
          ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
    
    - name: Wait for container to be ready
      run: |
        echo "Waiting for container to start..."
        sleep 10
        curl -f http://localhost:8000 || echo "Container might still be starting"
    
    - name: Show deployment info
      run: |
        echo "✅ Deployment successful!"
        echo "🐳 Docker Hub: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/expense-tracker"
        echo "🌐 Application is running at: http://localhost:8000"
        echo "📊 Container status:"
        docker ps | grep expense-tracker
